/**
 * PastQuest/Vectra - PDF Generation Service
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a PDF from structured lecture notes
 * @param {string} lectureId - Lecture ID
 * @param {Object} lecture - Lecture metadata
 * @param {Object} structuredNotes - Structured notes object with markdown field
 * @returns {Promise<string>} Path to the generated PDF file
 */
async function generatePDF(lectureId, lecture, structuredNotes) {
  return new Promise((resolve, reject) => {
    try {
      const tempDir = path.join(__dirname, '..', 'temp');
      if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
      }

      const filePath = path.join(tempDir, `lecture_${lectureId}.pdf`);
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text(lecture.topic, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(14).font('Helvetica').fillColor('#666')
        .text(`${lecture.course_code} - ${lecture.course_name}`, { align: 'center' });
      doc.fontSize(12).text(`Date: ${lecture.date} | Duration: ${Math.floor(lecture.duration / 60)} min`, { align: 'center' });
      if (lecture.lecturer) {
        doc.text(`Lecturer: ${lecture.lecturer}`, { align: 'center' });
      }
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke('#ddd');
      doc.moveDown(1);

      // Parse markdown into simple PDF content
      const lines = structuredNotes.markdown.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.3);
          continue;
        }

        if (trimmed.startsWith('# ')) {
          doc.fontSize(20).font('Helvetica-Bold').fillColor('#0F2A44').text(trimmed.replace('# ', ''));
          doc.moveDown(0.5);
        } else if (trimmed.startsWith('## ')) {
          doc.fontSize(16).font('Helvetica-Bold').fillColor('#0F2A44').text(trimmed.replace('## ', ''));
          doc.moveDown(0.3);
        } else if (trimmed.startsWith('### ')) {
          doc.fontSize(14).font('Helvetica-Bold').fillColor('#2E2E2E').text(trimmed.replace('### ', ''));
          doc.moveDown(0.2);
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          doc.fontSize(12).font('Helvetica').fillColor('#2E2E2E').text(`  \u2022 ${trimmed.substring(2)}`, { indent: 10 });
        } else if (/^\d+\.\s/.test(trimmed)) {
          doc.fontSize(12).font('Helvetica').fillColor('#2E2E2E').text(`  ${trimmed}`, { indent: 10 });
        } else if (trimmed.startsWith('$$') && trimmed.endsWith('$$')) {
          doc.fontSize(12).font('Courier').fillColor('#1FB6A6').text(trimmed.replace(/\$\$/g, ''), { align: 'center' });
        } else if (trimmed.includes('**')) {
          doc.fontSize(12).font('Helvetica').fillColor('#2E2E2E').text(trimmed.replace(/\*\*/g, ''));
        } else {
          doc.fontSize(12).font('Helvetica').fillColor('#2E2E2E').text(trimmed);
        }
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(10).font('Helvetica').fillColor('#999')
        .text('Generated by Vectra', { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve(filePath);
      });

      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = { generatePDF };
